# Generated by Django 5.2 on 2025-04-22 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_user_connex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='role_user_connex',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.role'),
        ),
        migrations.AlterField(
            model_name='role_user_connex',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='fournisseur_numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero', to=settings.AUTH_USER_MODEL)),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='users.number')),
            ],
        ),
    ]
